<section id="sleepbenefits">
    <form class="form create account form-create-account"
          action="<?= $block->getUrl('sleepbenefits/register/result') ?>"
          method="post"
          id="form-validate"
          enctype="multipart/form-data"
          autocomplete="off">

        <fieldset class="fieldset">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Enter your details to create an account.') ?></span></legend><br>

            <!-- Unique code input -->
            <div class="field required">
                <label for="text" class="label">
                    <span><?php /* @escapeNotVerified */ echo __('Company Code') ?></span>
                </label>

                <div class="control">
                    <input type="text" id="unique_code"
                           name="unique_code"
                           class="input-text"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('unique_code'))?>"/>
                </div>
            </div>

            <!-- Email input -->
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>

            <!-- Password input -->
            <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field password required">
                    <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input type="password" name="password" id="password"
                               title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               class="input-text"
                               data-password-min-length="8"
                               data-validate="{required:true, 'validate-customer-password':true}"
                               autocomplete="off">
                        <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                <?= $block->escapeHtml(__('No Password')) ?>
                            </span>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="field confirmation required">
                    <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                    <div class="control">
                        <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                    </div>
                </div>
            </fieldset>


        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>
            </div>
        </div>

    </form>
</section>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){

        var dataForm = $('#form-validate');

        dataForm.mage('validation', {
        }).find('input:text').attr('autocomplete', 'off');

    });
</script>
<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>


