<section id="sleepbenefits">
    <form class="form create account form-create-account"
          action="<?= $block->getUrl('sleepbenefits/register/result') ?>"
          method="post">

        <fieldset class="fieldset">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Enter your details to receive your invitation') ?></span></legend><br>

            <!-- Unique code input -->
            <div class="field required">
                <label for="text" class="label">
                    <span><?php /* @escapeNotVerified */ echo __('Your unique company code') ?></span>
                </label>

                <div class="control">
                    <input type="text" id="unique_code"
                           name="unique_code"
                           class="input-text"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('unique_code'))?>"/>
                </div>
            </div>

            <!-- Email input -->
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>


        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>
            </div>
        </div>

    </form>
</section>
